### ISSUE TITLE
Multiple Endpoints

### ISSUE THREAD

**Issue by cheluskin** [crudlio/crudl-connectors-base#8]
Hello. Typically, the API for pagination uses a separate endpoint, like /api/users/count, and it must be queried before the main query. What is the best way to do this in your architecture?

**Comment by sehmaschine** [comment]
That's interesting. I have (so far) never used an API with a separate endpoint for pagination. Can you refer to an example?

**Comment by cheluskin** [comment]
This approach uses loopback - a very popular solution for creating a server-side API https://strongloop.com/strongblog/working-with-pagination-and-loopback/

And it seems to me it makes sense. Know the size of the data to properly receive portions of this data.

**Comment by sehmaschine** [comment]
I'm personally more used to something like this:
http://www.django-rest-framework.org/api-guide/pagination/#pagenumberpagination

IMO the additional API call for counting the items is overhead, but we'll take a look.
My idea is this: Use a pagination middleware and do an additional API call with the given connector (since you know that the path is always `url/count`) and populate the pagination object with the result.

@vam does that sound reasonable?

**Comment by cheluskin** [comment]
`export default function paginationCreate() {

    return function addPaginationToResponse(next) {
        return {
            read: (req) => {
                req.url = req.url + "count";
                return next.read(req).then((res) => {

                    req.url = req.url.replace("count", "");
                    return next.read(req).then((res2) => {
                        res2.locals.pages = res.data.count && 0
                        return res2;
                    });

                    return res;
                })
            }
        };
    };
}`
Thank you for your help. I tried this method, but apparently I'm doing something wrong. I see both requests in the browser, everything looks good, but users are no longer output. Perhaps the data now does not reach the view.

**Comment by sehmaschine** [comment]
@cheluskin so we can close this ticket?

**Comment by vam** [comment]
@sehmaschine @cheluskin looks good!

**Comment by cheluskin** [comment]
@sehmaschine yes, please close
